accounts/urls.py
from django.urls import path
from accounts.views import login_view
from accounts.views import logout_view
from accounts.views import signup_view

app_name = "accounts"

urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", signup_view, name="signup"),
]

projects/urls.py
from django.urls import path, include
from projects.views import list_projects
from projects.views import show_project
from projects.views import create_view
from tasks.views import show_my_tasks


app_name = "projects"

urlpatterns = [
    path("", list_projects, name="list_projects"),
    path("<int:id>/", show_project, name="show_project"),
    path("create/", create_view, name="create_project"),
    path("tasks/", include("tasks.urls")),
]

tasks/urls.py
from django.urls import path
from tasks.views import create_task_view
from tasks.views import show_my_tasks

app_name = "tasks"

urlpatterns = [
    path("create/", create_task_view, name="create_task_task"),
    path("mine/", show_my_tasks, name="show_my_tasks"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.shortcuts import redirect
from accounts.views import login_view
from projects.views import list_projects


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", list_projects, name="home"),
    path("projects/", include("projects.urls", namespace="projects")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("login/", login_view, name="login"),
    path("tasks/", include("tasks.urls")),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(
        User, related_name="projects", on_delete=models.CASCADE, null=True
    )


def __str__(self):
    return self.name


# Create your models here.

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from projects.models import Project


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        User, null=True, related_name="tasks", on_delete=models.CASCADE
    )


# Create your models here.

accounts/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput, max_length=150)


class SignupForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput, max_length=150)
    password_confirmation = forms.CharField(
        widget=forms.PasswordInput, max_length=150
    )

projects/forms.py
from django import forms
from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ["name", "description", "owner"]

tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ["is_completed"]

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate
from .forms import LoginForm
from django.contrib.auth import login
from django.shortcuts import redirect
from django.contrib.auth import logout
from .forms import SignupForm
from django.contrib.auth.models import User


def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect("projects:list_projects")

    else:
        form = LoginForm()

    return render(request, "accounts/login.html", {"form": form})


def logout_view(request):
    logout(request)
    return redirect("accounts:login")


def signup_view(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password_confirmation"]

            if password == password_confirmation:
                user = User.objects.create_user(
                    username=username, password=password
                )
                login(request, user)
                return redirect("projects:list_projects")
            else:
                form.add_error(
                    "password_confirmation", "The passwords do not match"
                )
    else:
        form = SignupForm()

    return render(request, "accounts/signup.html", {"form": form})


# Create your views here.

projects/views.py
from django.shortcuts import render, redirect
from .models import Project
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from .forms import ProjectForm


@login_required
def list_projects(request):
    projects = Project.objects.filter(owner=request.user)
    return render(
        request, "projects/list_projects.html", {"projects": projects}
    )


def show_project(request, id):
    project = get_object_or_404(Project, id=id)
    return render(request, "projects/show_project.html", {"project": project})


@login_required
def create_view(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.owner = request.user
            project.save()
            return redirect("projects:list_projects")
    else:
        form = ProjectForm()

    return render(request, "projects/create_project.html", {"form": form})

tasks/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import TaskForm
from .models import Task


@login_required
def create_task_view(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save()
            return redirect(
                "projects:list_projects"
            )  # Adjust the name based on your project's URL configuration
    else:
        form = TaskForm()

    return render(request, "tasks/create_task.html", {"form": form})


@login_required
def show_my_tasks(request):
    tasks = Task.objects.filter(assignee=request.user)
    return render(request, "tasks/show_my_tasks.html", {"tasks": tasks})


# Create your views here.

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>

<body>

    <!-- Navigation -->
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'tasks:show_my_tasks' %}">My tasks</a></li>
                <li><a href="{% url 'projects:list_projects' %}">My projects</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
              {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        <div>
            <h1>Login</h1>

            <form action="{% url 'accounts:login' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit">Login</button>
            </form>

        </div>
    </main>

</body>

</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup</title>
</head>

<body>

    <!-- Navigation -->
    <header>
        <nav>
            <ul>
            {% if user.is_authenticated %}

                <li><a href="{% url 'tasks:show_my_tasks' %}">My tasks</a></li>
                <li><a href="{% url 'projects:list_projects' %}">My projects</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
            {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        <div>
            <h1>Signup</h1>

            <form action="{% url 'accounts:signup' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit">Signup</button>
            </form>

        </div>
    </main>

</body>

</html>

projects/templates/projects/create_project.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create a New Project</title>
</head>

<body>

    <!-- Navigation -->
    <header>
        <nav>
            <ul>
            {% if user.is_authenticated %}

                <li><a href="{% url 'tasks:show_my_tasks' %}">My tasks</a></li>
                <li><a href="{% url 'projects:list_projects' %}">My projects</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
            {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        <div>
            <h1>Create a new project</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>

</body>

</html>

projects/templates/projects/list_projects.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List of Projects</title>
</head>

<body>

    <!-- Navigation -->
    <header>
        <nav>
            <ul>
            {% if user.is_authenticated %}
                <li><a href="{% url 'tasks:show_my_tasks' %}">My tasks</a></li>
                <li><a href="{% url 'projects:list_projects' %}">My projects</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
            {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        <div>
            <h1>Project List</h1>
            <p><a href="{% url 'projects:create_project' %}">Create a new project</a></p>

            {% if projects %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Number of tasks</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in projects %}
                            <tr>
                                <td><a href="{% url 'projects:show_project' id=project.id %}">{{ project.name }}</td>
                                <td>{{ project.tasks.all|length }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>You are not assigned to any projects</p>
            {% endif %}

        </div>
    </main>

</body>

</html>

projects/templates/projects/show_project.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ project.name }} Details</title>
</head>

<body>


    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'tasks:show_my_tasks' %}">My tasks</a></li>
                <li><a href="{% url 'projects:list_projects' %}">My projects</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
          <li><a href="{% url 'accounts:login' %}">Login</a></li>
          <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <div>
            <h1>{{ project.name }}</h1>
            <p>{{ project.description }}</p>

            <h2>Tasks</h2>

            <p>
                <a href="{% url 'tasks:create_task' %}">Create a new task</a>
            </p>

            {% if project.tasks.all %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Assignee</th>
                            <th>Start date</th>
                            <th>Due date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in project.tasks.all %}
                            <tr>
                                <td>{{ task.name }}</td>
                                <td>{{ task.assignee.username }}</td>
                                <td>{{ task.start_date }}</td>
                                <td>{{ task.due_date }}</td>
                                <td>{{ task.is_completed|yesno:"yes,no" }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>This project has no tasks</p>
            {% endif %}
        </div>
    </main>

</body>

</html>

tasks/templates/tasks/create_task.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Task</title>
</head>

<body>

    <!-- Navigation -->
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'tasks:show_my_tasks' %}">My tasks</a></li>
                <li><a href="{% url 'projects:list_projects' %}">My projects</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
              {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        <div>
            <h1>Create a new task</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>

</body>

</html>

tasks/templates/tasks/show_my_tasks.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Tasks</title>
</head>

<body>
    <!-- Navigation -->
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'tasks:show_my_tasks' %}">My tasks</a></li>
                <li><a href="{% url 'projects:list_projects' %}">My projects</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
              {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        <div>
            <h1>My Tasks</h1>

            {% if tasks %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start date</th>
                            <th>Due date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in tasks %}
                            <tr>
                                <td>{{ task.name }}</td>
                                <td>{{ task.start_date }}</td>
                                <td>{{ task.due_date }}</td>
                                <td>{{ task.is_completed|yesno:"yes,no" }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>You have no tasks</p>
            {% endif %}
        </div>
    </main>

</body>

</html>